from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(271, 379)
        MainWindow.setFocusPolicy(QtCore.Qt.NoFocus)
        MainWindow.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./image/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setWindowOpacity(1.0)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 271, 380))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.layoutWidget = QtWidgets.QWidget(self.tab)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 200, 161, 155))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_Card_7 = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btn_Card_7.setFont(font)
        self.btn_Card_7.setObjectName("btn_Card_7")
        self.horizontalLayout.addWidget(self.btn_Card_7)
        self.btn_Card_8 = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btn_Card_8.setFont(font)
        self.btn_Card_8.setObjectName("btn_Card_8")
        self.horizontalLayout.addWidget(self.btn_Card_8)
        self.btn_Card_9 = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btn_Card_9.setFont(font)
        self.btn_Card_9.setObjectName("btn_Card_9")
        self.horizontalLayout.addWidget(self.btn_Card_9)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_Card_4 = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btn_Card_4.setFont(font)
        self.btn_Card_4.setStyleSheet("color: rgb(0, 170, 255);")
        self.btn_Card_4.setObjectName("btn_Card_4")
        self.horizontalLayout_2.addWidget(self.btn_Card_4)
        self.btn_Card_5 = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btn_Card_5.setFont(font)
        self.btn_Card_5.setStyleSheet("color: rgb(0, 170, 255);")
        self.btn_Card_5.setObjectName("btn_Card_5")
        self.horizontalLayout_2.addWidget(self.btn_Card_5)
        self.btn_Card_6 = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btn_Card_6.setFont(font)
        self.btn_Card_6.setStyleSheet("color: rgb(0, 170, 255);")
        self.btn_Card_6.setObjectName("btn_Card_6")
        self.horizontalLayout_2.addWidget(self.btn_Card_6)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btn_Card_1 = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btn_Card_1.setFont(font)
        self.btn_Card_1.setStyleSheet("color: rgb(255, 0, 0);")
        self.btn_Card_1.setObjectName("btn_Card_1")
        self.horizontalLayout_3.addWidget(self.btn_Card_1)
        self.btn_Card_2 = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btn_Card_2.setFont(font)
        self.btn_Card_2.setStyleSheet("color: rgb(0, 170, 255);")
        self.btn_Card_2.setObjectName("btn_Card_2")
        self.horizontalLayout_3.addWidget(self.btn_Card_2)
        self.btn_Card_3 = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btn_Card_3.setFont(font)
        self.btn_Card_3.setStyleSheet("color: rgb(0, 170, 255);")
        self.btn_Card_3.setObjectName("btn_Card_3")
        self.horizontalLayout_3.addWidget(self.btn_Card_3)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.btn_highCards = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btn_highCards.setFont(font)
        self.btn_highCards.setStyleSheet("color: rgb(255, 0, 0);")
        self.btn_highCards.setObjectName("btn_highCards")
        self.verticalLayout.addWidget(self.btn_highCards)
        self.btn_Reset = QtWidgets.QPushButton(self.tab)
        self.btn_Reset.setGeometry(QtCore.QRect(180, 320, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btn_Reset.setFont(font)
        self.btn_Reset.setStyleSheet("color: rgb(103, 0, 1);")
        self.btn_Reset.setObjectName("btn_Reset")
        self.txt_RunCount = QtWidgets.QTextEdit(self.tab)
        self.txt_RunCount.setGeometry(QtCore.QRect(190, 10, 71, 41))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.txt_RunCount.setFont(font)
        self.txt_RunCount.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.txt_RunCount.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.txt_RunCount.setInputMethodHints(QtCore.Qt.ImhNone)
        self.txt_RunCount.setReadOnly(True)
        self.txt_RunCount.setObjectName("txt_RunCount")
        self.lbl_RunCount = QtWidgets.QLabel(self.tab)
        self.lbl_RunCount.setGeometry(QtCore.QRect(10, 10, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_RunCount.setFont(font)
        self.lbl_RunCount.setStyleSheet("color: rgb(153, 0, 0);\n"
"background-color: rgb(209, 209, 209);")
        self.lbl_RunCount.setObjectName("lbl_RunCount")
        self.txt_TrueCount = QtWidgets.QTextEdit(self.tab)
        self.txt_TrueCount.setGeometry(QtCore.QRect(190, 60, 71, 41))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.txt_TrueCount.setFont(font)
        self.txt_TrueCount.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.txt_TrueCount.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.txt_TrueCount.setInputMethodHints(QtCore.Qt.ImhNone)
        self.txt_TrueCount.setReadOnly(True)
        self.txt_TrueCount.setObjectName("txt_TrueCount")
        self.lbl_TrueCount = QtWidgets.QLabel(self.tab)
        self.lbl_TrueCount.setGeometry(QtCore.QRect(10, 60, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_TrueCount.setFont(font)
        self.lbl_TrueCount.setStyleSheet("color: rgb(0, 198, 0);\n"
"background-color: rgb(209, 209, 209);")
        self.lbl_TrueCount.setObjectName("lbl_TrueCount")
        self.btn_Basic = QtWidgets.QPushButton(self.tab)
        self.btn_Basic.setGeometry(QtCore.QRect(180, 280, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btn_Basic.setFont(font)
        self.btn_Basic.setObjectName("btn_Basic")
        self.txt_lowCard = QtWidgets.QTextEdit(self.tab)
        self.txt_lowCard.setGeometry(QtCore.QRect(90, 120, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.txt_lowCard.setFont(font)
        self.txt_lowCard.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.txt_lowCard.setStyleSheet("")
        self.txt_lowCard.setInputMethodHints(QtCore.Qt.ImhNone)
        self.txt_lowCard.setReadOnly(True)
        self.txt_lowCard.setObjectName("txt_lowCard")
        self.lbl_lowCard = QtWidgets.QLabel(self.tab)
        self.lbl_lowCard.setGeometry(QtCore.QRect(10, 120, 81, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_lowCard.sizePolicy().hasHeightForWidth())
        self.lbl_lowCard.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_lowCard.setFont(font)
        self.lbl_lowCard.setStyleSheet("background-color: rgb(223, 223, 223);\n"
"color: rgb(0, 170, 255);")
        self.lbl_lowCard.setScaledContents(False)
        self.lbl_lowCard.setObjectName("lbl_lowCard")
        self.txt_middleCard = QtWidgets.QTextEdit(self.tab)
        self.txt_middleCard.setGeometry(QtCore.QRect(90, 160, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.txt_middleCard.setFont(font)
        self.txt_middleCard.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.txt_middleCard.setStyleSheet("")
        self.txt_middleCard.setInputMethodHints(QtCore.Qt.ImhNone)
        self.txt_middleCard.setReadOnly(True)
        self.txt_middleCard.setObjectName("txt_middleCard")
        self.lbl_middleCard = QtWidgets.QLabel(self.tab)
        self.lbl_middleCard.setGeometry(QtCore.QRect(10, 160, 81, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_middleCard.sizePolicy().hasHeightForWidth())
        self.lbl_middleCard.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_middleCard.setFont(font)
        self.lbl_middleCard.setStyleSheet("background-color: rgb(223, 223, 223);")
        self.lbl_middleCard.setScaledContents(False)
        self.lbl_middleCard.setObjectName("lbl_middleCard")
        self.lbl_highCard = QtWidgets.QLabel(self.tab)
        self.lbl_highCard.setGeometry(QtCore.QRect(140, 120, 71, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_highCard.sizePolicy().hasHeightForWidth())
        self.lbl_highCard.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_highCard.setFont(font)
        self.lbl_highCard.setStyleSheet("background-color: rgb(223, 223, 223);\n"
"color: rgb(255, 0, 0);")
        self.lbl_highCard.setScaledContents(False)
        self.lbl_highCard.setObjectName("lbl_highCard")
        self.txt_highCard = QtWidgets.QTextEdit(self.tab)
        self.txt_highCard.setGeometry(QtCore.QRect(210, 120, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.txt_highCard.setFont(font)
        self.txt_highCard.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.txt_highCard.setStyleSheet("")
        self.txt_highCard.setInputMethodHints(QtCore.Qt.ImhNone)
        self.txt_highCard.setReadOnly(True)
        self.txt_highCard.setObjectName("txt_highCard")
        self.lbl_totalCard = QtWidgets.QLabel(self.tab)
        self.lbl_totalCard.setGeometry(QtCore.QRect(140, 160, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_totalCard.setFont(font)
        self.lbl_totalCard.setAutoFillBackground(False)
        self.lbl_totalCard.setStyleSheet("background-color: rgb(223, 223, 223);")
        self.lbl_totalCard.setObjectName("lbl_totalCard")
        self.txt_totalCard = QtWidgets.QTextEdit(self.tab)
        self.txt_totalCard.setGeometry(QtCore.QRect(210, 160, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.txt_totalCard.setFont(font)
        self.txt_totalCard.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.txt_totalCard.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 127);")
        self.txt_totalCard.setInputMethodHints(QtCore.Qt.ImhNone)
        self.txt_totalCard.setReadOnly(True)
        self.txt_totalCard.setObjectName("txt_totalCard")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.txt_Decks = QtWidgets.QTextEdit(self.tab_2)
        self.txt_Decks.setGeometry(QtCore.QRect(170, 20, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.txt_Decks.setFont(font)
        self.txt_Decks.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.txt_Decks.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.txt_Decks.setInputMethodHints(QtCore.Qt.ImhNone)
        self.txt_Decks.setMidLineWidth(0)
        self.txt_Decks.setLineWrapColumnOrWidth(0)
        self.txt_Decks.setOverwriteMode(False)
        self.txt_Decks.setAcceptRichText(True)
        self.txt_Decks.setObjectName("txt_Decks")
        self.lbl_Decks = QtWidgets.QLabel(self.tab_2)
        self.lbl_Decks.setGeometry(QtCore.QRect(50, 20, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_Decks.setFont(font)
        self.lbl_Decks.setObjectName("lbl_Decks")
        self.layoutWidget1 = QtWidgets.QWidget(self.tab_2)
        self.layoutWidget1.setGeometry(QtCore.QRect(30, 280, 211, 71))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btn_Start = QtWidgets.QPushButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btn_Start.setFont(font)
        self.btn_Start.setStyleSheet("color: rgb(0, 184, 0);")
        self.btn_Start.setObjectName("btn_Start")
        self.horizontalLayout_4.addWidget(self.btn_Start)
        self.btn_Stop = QtWidgets.QPushButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btn_Stop.setFont(font)
        self.btn_Stop.setStyleSheet("color: rgb(103, 0, 1);")
        self.btn_Stop.setObjectName("btn_Stop")
        self.horizontalLayout_4.addWidget(self.btn_Stop)
        self.layoutWidget2 = QtWidgets.QWidget(self.tab_2)
        self.layoutWidget2.setGeometry(QtCore.QRect(30, 130, 211, 61))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lbl_CountStrategy = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_CountStrategy.setFont(font)
        self.lbl_CountStrategy.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbl_CountStrategy.setAutoFillBackground(False)
        self.lbl_CountStrategy.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_CountStrategy.setObjectName("lbl_CountStrategy")
        self.verticalLayout_2.addWidget(self.lbl_CountStrategy)
        self.cb_Strategy = QtWidgets.QComboBox(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(16)
        self.cb_Strategy.setFont(font)
        self.cb_Strategy.setObjectName("cb_Strategy")
        self.cb_Strategy.addItem("")
        self.cb_Strategy.addItem("")
        self.cb_Strategy.addItem("")
        self.cb_Strategy.addItem("")
        self.verticalLayout_2.addWidget(self.cb_Strategy)
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 271, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "BlackJack Card Counter"))
        self.btn_Card_7.setText(_translate("MainWindow", "7"))
        self.btn_Card_8.setText(_translate("MainWindow", "8"))
        self.btn_Card_9.setText(_translate("MainWindow", "9"))
        self.btn_Card_4.setText(_translate("MainWindow", "4"))
        self.btn_Card_5.setText(_translate("MainWindow", "5"))
        self.btn_Card_6.setText(_translate("MainWindow", "6"))
        self.btn_Card_1.setText(_translate("MainWindow", "A"))
        self.btn_Card_2.setText(_translate("MainWindow", "2"))
        self.btn_Card_3.setText(_translate("MainWindow", "3"))
        self.btn_highCards.setText(_translate("MainWindow", "10 - J Q K A"))
        self.btn_Reset.setText(_translate("MainWindow", "Reset"))
        self.lbl_RunCount.setText(_translate("MainWindow", "Running Count :"))
        self.lbl_TrueCount.setText(_translate("MainWindow", "TRUE Count :"))
        self.btn_Basic.setText(_translate("MainWindow", "Strategy"))
        self.lbl_lowCard.setText(_translate("MainWindow", "Low Card :"))
        self.lbl_middleCard.setText(_translate("MainWindow", "Middle Card :"))
        self.lbl_highCard.setText(_translate("MainWindow", "High Card :"))
        self.lbl_totalCard.setText(_translate("MainWindow", "Total Cards :"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Game"))
        self.txt_Decks.setPlaceholderText(_translate("MainWindow", "8"))
        self.lbl_Decks.setText(_translate("MainWindow", "Decks :"))
        self.btn_Start.setText(_translate("MainWindow", "START"))
        self.btn_Stop.setText(_translate("MainWindow", "STOP"))
        self.lbl_CountStrategy.setText(_translate("MainWindow", "Count Strategy"))
        self.cb_Strategy.setItemText(0, _translate("MainWindow", "Hi-Lo"))
        self.cb_Strategy.setItemText(1, _translate("MainWindow", "Hi-Opt 2"))
        self.cb_Strategy.setItemText(2, _translate("MainWindow", "Uston APC"))
        self.cb_Strategy.setItemText(3, _translate("MainWindow", "Omega 2"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Settings"))



if __name__ == "__main__":
    import sys
    import image_rc
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
